import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import typedocSidebar from "./docs/api/typedoc-sidebar";

const enhanceWithGeneratedIndexes = (items: typeof typedocSidebar.items) => {
	return items.map((item) => {
		if (item.type === "category") {
			item.link = {
				type: "generated-index",
				title: item.label,
				description: `API ${item.label}`,
				slug: `/api/${item.label.toLowerCase().replace(/\s+/g, "-")}`,
			};
		}
		return item;
	});
};

const sidebars: SidebarsConfig = {
	docs: [
		{
			type: "autogenerated",
			dirName: "main",
		},
		{
			type: "category",
			label: "API",
			link: {
				type: "generated-index",
				title: "API Reference",
				description: "Classes, interfaces, type aliases and functions",
				slug: "/api",
			},
			items: enhanceWithGeneratedIndexes(typedocSidebar.items),
			collapsed: false,
		},
	],
};

export default sidebars;
